package com.hungrylab.backend.Entity;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;

@Entity
@Table(name = "Payment")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class Payment {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // The order this payment is attached to
    @OneToOne
    @JoinColumn(name = "order_id", nullable = false)
    private Order order;

    // The ID generated by Razorpay when you CREATE the order (e.g., order_Pkjd...)
    private String razorpayOrderId; 

    // The payment ID sent in the webhook when the user actually pays (e.g., pay_Pkjd...)
    private String razorpayPaymentId;
    
    // Webhook signature sent by Razorpay
    private String razorpaySignature;

    // PENDING, SUCCESS, FAILED
    private String status;

    private LocalDateTime createdAt = LocalDateTime.now();
    private LocalDateTime updatedAt = LocalDateTime.now();
}
